""" Each new term in the Fibonacci sequence is generated by adding the previous two terms.

By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

def fib() -> int:
    _all_fib = [1, 2]
    _n = 0

    while _n <= 4_000_000:
        _n = _all_fib[-2] + _all_fib[-1]
        _all_fib.append(_n)

    even_fib = [x for x in _all_fib if x % 2 == 0]

    _result = sum(even_fib)

    return _result


if __name__ == '__main__':
    result = fib()

    print(result)



